
services:
  gmail_tool:
    build: ./langgraph
    container_name: gmail_tool
    volumes:
    - ./credentials:/app/credentials:rw
    environment:
      PYTHONUNBUFFERED: 1
      REDIS_URL: redis://redis:6379/0
      # Import from .env file
      LANGSMITH_API_KEY: ${LANGSMITH_API_KEY}
      LANGSMITH_TRACING: ${LANGSMITH_TRACING}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      GOOGLE_SHEET_ID: ${GOOGLE_SHEET_ID}
      GOOGLE_SHEETS_CREDENTIALS: ${GOOGLE_SHEETS_CREDENTIALS}
      GOOGLE_SHEET_NAME: ${GOOGLE_SHEET_NAME}
    depends_on:
      redis:
        condition: service_healthy
    command: ["bash", "-lc", "python run_daily.py && python main.py"]
    restart: "no"

  redis:
    image: redis:alpine
    container_name: gmail_redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 2s
      timeout: 5s
      retries: 20
    restart: unless-stopped


  redis-sub:
    build: ./sub
    container_name: gmail_subscriber
    environment:
      PYTHONUNBUFFERED: 1
      REDIS_URL: redis://redis:6379/0
      SENDER_EMAIL:  ${SENDER_EMAIL}
      SENDER_EMAIL_PASSWORD: ${SENDER_EMAIL_PASSWORD}
      RECEIVER_EMAIL: ${RECEIVER_EMAIL}
    depends_on:
      redis:
        condition: service_healthy
    command: python main.py
    restart: unless-stopped
    
